######################################################################
# Automatically generated by qmake (1.07a) Tue Oct 3 03:26:17 2006
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
INTERFACES += form1.ui
