######################################################################
# Automatically generated by qmake (1.07a) Tue Nov 7 13:42:15 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += canvas.h form.h
SOURCES += canvas.cpp form.cpp main.cpp
