#! /bin/bash
#echo -n "blue, yellow, red:"
#read -e COLOR
#setterm -background $COLOR
#echo It is a $COLOR day
clear
#echo -e "\033[1m BOLD \033[5m DIM \033[5m fLASH! \033[0m"
echo -e "\033\31m "
more /dept/vicky/2003/$1
echo -e "\033[7m \033[0m"
