######################################################################
# Automatically generated by qmake (1.07a) Thu Oct 5 01:08:36 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += metric_conversion.ui.h
INTERFACES += metric_conversion.ui
SOURCES += main.cpp
